version: "3.8"
services:
    php-micro-service-stock:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: micro_service_stock_php
        # restart: always
        tty: true
        working_dir: /var/www/html/
        volumes:
            - ./:/var/www/html/
            - ./php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
        networks:
            - micro_service_aleira-micro-network

    nginx_micro_service_stock:
        depends_on:
            - php-micro-service-stock
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx_micro_service_stock
        # restart: always
        tty: true
        ports:
            - "${APP_PORT}:80"
        networks:
            - micro_service_aleira-micro-network

    mysql_micro_service_stock:
        image: mariadb
        container_name: db-micro-service-stock
        env_file:
            - .env
        environment:
            MARIADB_DATABASE: ${DB_DATABASE}
            MARIADB_USER: ${DB_USERNAME}
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            MARIADB_PASSWORD: ${DB_PASSWORD}
        ports:
        - "${DB_PORT}:3306"
        volumes:
        - mysql_micro_service_stock:/var/lib/mysql
        - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
        networks:
        - micro_service_aleira-micro-network

volumes:
    mysql_micro_service_stock:

networks:
    micro_service_aleira-micro-network:
