version: "3.8"
services:
    php_micro_service_deliveries:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: micro_service_deliveries_php
        # restart: always
        tty: true
        working_dir: /var/www/html/
        volumes:
            - ./:/var/www/html/
            - ./php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
        networks:
            - micro_service_deliveries-micro-network

    nginx_micro_service_deliveries:
        depends_on:
            - php_micro_service_deliveries
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx_micro_service_deliveries
        # restart: always
        tty: true
        ports:
            - "${APP_PORT}:80"
        networks:
            - micro_service_deliveries-micro-network

    mysql_micro_service_deliveries:
        image: mariadb
        container_name: db_micro_service_deliveries
        env_file:
            - .env
        environment:
            MARIADB_DATABASE: ${DB_DATABASE}
            MARIADB_USER: ${DB_USERNAME}
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            MARIADB_PASSWORD: ${DB_PASSWORD}
        ports:
        - "${DB_PORT}:3306"
        volumes:
        - mysql_micro_service_deliveries:/var/lib/mysql
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
        - micro_service_deliveries-micro-network

volumes:
    mysql_micro_service_deliveries:

networks:
    micro_service_deliveries-micro-network:
