name: CI/CD Workflow with Laravel and Docker

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install PHP Dependencies
      run: sudo apt-get install -y librdkafka-dev php-pear
    - name: Install PHP rdkafka
      run: sudo pecl install rdkafka
    - name: Install Dependencies
      run: composer install --ignore-platform-req=ext-rdkafka
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
  build-image:
    runs-on: ubuntu-latest
    needs: laravel-tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t micro_service_stock_php .

      - name: Run Docker Container
        run: docker run -d -p 8000:8000 --name my_container_test micro_service_stock_php

