name: CI/CD Workflow with Laravel and Docker

on:
  push:
    branches:
      - dev
      - master

jobs:
  build-image-and-run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t micro_service_deliveries_php .

      - name: Run Docker Container
        run: docker run -d -p 8000:8000 --name my_container_test micro_service_deliveries_php

      - name: Run Laravel Tests
        run: docker exec my_container_test /bin/sh -c "php artisan test"
      - name: Show Container Logs
        run: docker logs my_container_test
